### ISSUE TITLE
Implement limits on client operations.

### ISSUE THREAD

**Issue by jmalloc** [rinq/httpd#3]
- [x] maximum timeout for synchronous calls - see #14 
- [ ] maximum concurrent synchronous calls - see #15 
- [ ] maximum websocket frame size - see #16
